import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Lang = "ar" | "en";
type Theme = "dark" | "light";

type Dict = Record<string, { ar: string; en: string }>;

const dict: Dict = {
  appName: { ar: "فارما ليدجر", en: "PharmLedger" },
  tagline: { ar: "الإدارة المالية للصيدليات", en: "Pharmacy Financial Management" },

  // Nav
  dashboard: { ar: "لوحة التحكم", en: "Dashboard" },
  revenue: { ar: "الإيرادات", en: "Revenue" },
  expenses: { ar: "المصروفات", en: "Expenses" },
  purchases: { ar: "المشتريات", en: "Purchases" },
  suppliers: { ar: "الموردون", en: "Suppliers" },
  staff: { ar: "الموظفون", en: "Staff" },
 debts: { ar: "الديون", en: "Debts" },
 supplierPayments: { ar: "سندات سداد الموردين", en: "Supplier Payments" },
  statements: { ar: "القوائم المالية", en: "Statements" },
  vat: { ar: "ضريبة القيمة المضافة", en: "VAT" },
  reports: { ar: "التقارير", en: "Reports" },
  settings: { ar: "الإعدادات", en: "Settings" },
  backup: { ar: "النسخ الاحتياطي", en: "Backup" },
  accounts: { ar: "الحسابات", en: "Accounts" },
  inventory: { ar: "المخزون", en: "Inventory" },
  inventoryProducts: { ar: "المنتجات", en: "Products" },
  inventoryOperations: { ar: "العمليات", en: "Operations" },
  inventoryReports: { ar: "التقارير", en: "Reports" },
  productsTab: { ar: "المنتجات", en: "Products" },
  productVariantsTab: { ar: "متغيرات المنتج", en: "Product Variants" },
  lotSerialTab: { ar: "أرقام التشغيل/التسلسل", en: "Lot / Serial Numbers" },
  packagesTab: { ar: "العبوات", en: "Packages" },
  createProduct: { ar: "إنشاء منتج", en: "Create Product" },
  editProduct: { ar: "تعديل المنتج", en: "Edit Product" },
  productName: { ar: "اسم المنتج", en: "Product Name" },
  productNameAr: { ar: "اسم المنتج بالعربية", en: "Product Name (Arabic)" },
  productNameEn: { ar: "اسم المنتج بالإنجليزية", en: "Product Name (English)" },
  productSku: { ar: "SKU", en: "SKU" },
  productCategory: { ar: "تصنيف المنتج", en: "Product Category" },
  productUnit: { ar: "الوحدة", en: "Unit" },
  productPrice: { ar: "السعر", en: "Price" },
  productCost: { ar: "التكلفة", en: "Cost" },
  productBarcode: { ar: "الباركود", en: "Barcode" },
  intlBarcode: { ar: "الباركود الدولي", en: "International Barcode" },
  sfdaCode: { ar: "كود الـ SFDA", en: "SFDA Code" },
  costExTax: { ar: "سعر التكلفة (بدون ضريبة)", en: "Cost Price (Excl. Tax)" },
  priceIncTax: { ar: "سعر البيع (شامل الضريبة)", en: "Sale Price (Incl. Tax)" },
  purchaseTax: { ar: "ضريبة المشتريات", en: "Purchase Tax" },
  salesTax: { ar: "ضريبة المبيعات", en: "Sales Tax" },
  taxZero: { ar: "صفر %", en: "0%" },
  taxFifteen: { ar: "15%", en: "15%" },
  onHandQty: { ar: "الكمية المتوفرة", en: "On Hand QTY" },
  forecastedQty: { ar: "الكمية المتوقعة", en: "Forecasted QTY" },
  sfdaTracking: { ar: "تتبع SFDA", en: "SFDA Tracking" },
  sfdaTrackingHint: { ar: "فعّل إذا كان المنتج يتطلب تتبع SFDA", en: "Enable if this product requires SFDA tracking" },
  lotsSerials: { ar: "أرقام التشغيل / التسلسل", en: "Lot / Serial Numbers" },
  lotNumber: { ar: "رقم التشغيلة / التسلسل", en: "Lot / Serial #" },
  expiryDate: { ar: "تاريخ الانتهاء", en: "Expiry Date" },
  lotQty: { ar: "الكمية", en: "Quantity" },
  addLot: { ar: "إضافة رقم تشغيلة", en: "Add Lot / Serial" },
  noLots: { ar: "لا توجد أرقام تشغيلة بعد", en: "No lots / serials yet" },
  lotRequired: { ar: "هذا المنتج يتطلب تتبع SFDA — أضف رقم تشغيلة واحد على الأقل", en: "This product requires SFDA tracking — add at least one lot/serial" },
  lotNumberRequired: { ar: "رقم التشغيلة مطلوب", en: "Lot/serial number is required" },
  product: { ar: "المنتج", en: "Product" },
  noSfdaProducts: { ar: "لا توجد منتجات مفعّل لها تتبع SFDA", en: "No SFDA-tracked products yet" },
  basicInfo: { ar: "البيانات الأساسية", en: "Basic Information" },
  pricing: { ar: "التسعير والضرائب", en: "Pricing & Taxes" },
  stockInfo: { ar: "المخزون", en: "Stock" },
  noProducts: { ar: "لا توجد منتجات بعد", en: "No products yet" },
  productMedia: { ar: "صور المنتج", en: "Product Images" },
  addImage: { ar: "إضافة صورة", en: "Add Image" },
  imageTooLarge: { ar: "حجم الصورة كبير جدًا (الحد الأقصى 2 ميجابايت)", en: "Image too large (max 2MB)" },
  productDetails: { ar: "تفاصيل ووصف المنتج", en: "Product Details" },
  productDescription: { ar: "وصف المنتج", en: "Product Description" },
  productUsage: { ar: "طريقة الاستخدام", en: "Usage Instructions" },
  totalCostValue: { ar: "إجمالي التكلفة", en: "Total Cost" },
  totalSaleValue: { ar: "إجمالي البيع", en: "Total Sale" },
  totalSalesTax: { ar: "إجمالي ضريبة البيع", en: "Total Sales Tax" },
  totals: { ar: "الإجماليات", en: "Totals" },
  totalAmount: { ar: "إجمالي المبلغ", en: "Total Amount" },
  totalPaid: { ar: "إجمالي المدفوع", en: "Total Paid" },
  totalBalance: { ar: "إجمالي الرصيد", en: "Total Balance" },
  profitMargin: { ar: "نسبة الربح", en: "Profit Margin" },
  groupByNone: { ar: "بدون تجميع", en: "No Grouping" },
  allCategories: { ar: "كل التصنيفات", en: "All Categories" },
  allTaxes: { ar: "كل الضرائب", en: "All Taxes" },
  sfdaStatus: { ar: "حالة تتبع SFDA", en: "SFDA Status" },
  allProducts: { ar: "كل المنتجات", en: "All Products" },
  sfdaOnly: { ar: "بتتبع SFDA فقط", en: "SFDA Tracked Only" },
  nonSfdaOnly: { ar: "بدون تتبع SFDA", en: "Non-SFDA Only" },
  exportProductsExcel: { ar: "تصدير إلى Excel", en: "Export to Excel" },
  importProductsExcel: { ar: "استيراد من Excel", en: "Import from Excel" },
  downloadTemplateBtn: { ar: "تنزيل القالب", en: "Download Template" },
  importedProducts: { ar: "تم استيراد {n} منتج", en: "Imported {n} products" },
  importNoRowsFound: { ar: "لم يتم العثور على صفوف صالحة", en: "No valid rows found" },
  importFailedMsg: { ar: "فشل الاستيراد", en: "Import failed" },
  uncategorized: { ar: "بدون تصنيف", en: "Uncategorized" },

  chartOfAccounts: { ar: "شجرة الحسابات", en: "Chart of Accounts" },
  chartOfAccountsSubtitle: { ar: "الدليل المحاسبي والتصنيفات الرئيسية للحسابات", en: "Accounting directory and main account classifications" },
  accountCode: { ar: "الكود", en: "Code" },
  accountName: { ar: "اسم الحساب", en: "Account Name" },
  accountType: { ar: "النوع", en: "Type" },
  accountNature: { ar: "الطبيعة", en: "Nature" },
  natureDebit: { ar: "مدين", en: "Debit" },
  natureCredit: { ar: "دائن", en: "Credit" },
  addRootAccount: { ar: "إضافة تصنيف رئيسي", en: "Add Main Category" },
  addSubAccount: { ar: "إضافة تصنيف فرعي", en: "Add Sub-category" },
  editName: { ar: "تعديل الاسم", en: "Edit Name" },
  deleteAccount: { ar: "حذف", en: "Delete" },
  confirmDeleteAccount: { ar: "حذف هذا التصنيف وكل ما تحته؟", en: "Delete this account and all its children?" },
  newAccountName: { ar: "اسم التصنيف الجديد", en: "New category name" },
  resetToDefault: { ar: "استعادة الافتراضي", en: "Reset to default" },
  journalAndLedger: { ar: "قيود اليومية ودفتر الأستاذ", en: "Journal & Ledger" },
  journalSubtitle: { ar: "قيود محاسبية مزدوجة مولدة تلقائياً من كل الموديولات", en: "Double-entry journal auto-generated from all modules" },
  journal: { ar: "اليومية", en: "Journal" },
  ledger: { ar: "دفتر الأستاذ", en: "Ledger" },
  ledgerPickAccount: { ar: "اختر حساباً لعرض حركاته", en: "Select an account to view its movements" },
  selectAccount: { ar: "اختر حساباً", en: "Select an account" },
  allAccounts: { ar: "كل الحسابات", en: "All accounts" },
  source: { ar: "المصدر", en: "Source" },
  debit: { ar: "مدين", en: "Debit" },
  credit: { ar: "دائن", en: "Credit" },
  totalDebit: { ar: "إجمالي المدين", en: "Total Debit" },
  totalCredit: { ar: "إجمالي الدائن", en: "Total Credit" },
  difference: { ar: "الفرق", en: "Difference" },
  description: { ar: "البيان", en: "Description" },
  noJournalLines: { ar: "لا توجد قيود مطابقة", en: "No matching entries" },
  refresh: { ar: "تحديث", en: "Refresh" },
  all: { ar: "الكل", en: "All" },
  linkedAccount: { ar: "حساب مرتبط (اختياري)", en: "Linked account (optional)" },







  // Dashboard
  welcome: { ar: "مرحباً بعودتك", en: "Welcome back" },
  overview: { ar: "نظرة عامة على أداء صيدليتك اليوم", en: "Here's how your pharmacy is performing today" },
  todayRevenue: { ar: "إيرادات اليوم", en: "Today's Revenue" },
  todayExpenses: { ar: "مصروفات اليوم", en: "Today's Expenses" },
  netProfit: { ar: "صافي الربح (الشهر)", en: "Net Profit (MTD)" },
  outstandingDebts: { ar: "الديون المستحقة", en: "Outstanding Debts" },
  cashBalance: { ar: "الرصيد النقدي", en: "Cash Balance" },
  vatDue: { ar: "ض. القيمة المضافة المستحقة", en: "VAT Due This Month" },
  vsYesterday: { ar: "مقارنة بالأمس", en: "vs yesterday" },

  revenueVsExpenses: { ar: "الإيرادات مقابل المصروفات", en: "Revenue vs Expenses" },
  last30: { ar: "آخر 30 يوماً", en: "Last 30 days" },
  paymentMix: { ar: "طرق الدفع", en: "Revenue by Payment Method" },
  monthlyProfit: { ar: "الربح الشهري", en: "Monthly Profit" },
  cashFlow: { ar: "التدفق النقدي", en: "Cash Flow" },
  last90: { ar: "آخر 90 يوماً", en: "Last 90 days" },
  recentTransactions: { ar: "أحدث المعاملات", en: "Recent Transactions" },
  topSuppliers: { ar: "أهم الموردين", en: "Top Suppliers" },
  overdueDebts: { ar: "الديون المتأخرة", en: "Overdue Debts" },

  // Quick actions
  addRevenue: { ar: "إضافة إيراد", en: "Add Revenue" },
  addExpense: { ar: "إضافة مصروف", en: "Add Expense" },
  newPurchase: { ar: "فاتورة شراء", en: "New Purchase" },
  logShift: { ar: "تسجيل مناوبة", en: "Log Shift" },

  // Table headers / labels
  date: { ar: "التاريخ", en: "Date" },
  category: { ar: "التصنيف", en: "Category" },
  amount: { ar: "المبلغ", en: "Amount" },
  type: { ar: "النوع", en: "Type" },
  status: { ar: "الحالة", en: "Status" },
  party: { ar: "الجهة", en: "Party" },
  daysOverdue: { ar: "أيام التأخير", en: "Days Overdue" },
  totalPurchases: { ar: "إجمالي المشتريات", en: "Total Purchases" },

  income: { ar: "إيراد", en: "Income" },
  expense: { ar: "مصروف", en: "Expense" },
  cash: { ar: "نقدي", en: "Cash" },
  card: { ar: "بطاقة", en: "Card" },
  transfer: { ar: "تحويل", en: "Transfer" },
  insurance: { ar: "تأمين", en: "Insurance" },

  search: { ar: "بحث...", en: "Search..." },
  admin: { ar: "مدير", en: "Admin" },

  currency: { ar: "ر.س", en: "SAR" },

  // Revenue module
  revenueTitle: { ar: "إدارة الإيرادات", en: "Revenue Management" },
  revenueSubtitle: { ar: "تتبع وإدارة جميع إيرادات الصيدلية", en: "Track and manage all pharmacy income" },
  totalRevenue: { ar: "إجمالي الإيرادات", en: "Total Revenue" },
  avgTicket: { ar: "متوسط الفاتورة", en: "Average Ticket" },
  transactionsCount: { ar: "عدد المعاملات", en: "Transactions" },
  topCategory: { ar: "أعلى تصنيف", en: "Top Category" },
  newRevenue: { ar: "إيراد جديد", en: "New Revenue Entry" },
  filterAll: { ar: "الكل", en: "All" },
  searchRevenue: { ar: "بحث في الإيرادات...", en: "Search revenue..." },
  exportCsv: { ar: "تصدير Excel", en: "Export Excel" },
  exportExcel: { ar: "تصدير Excel", en: "Export Excel" },
  exportPdf: { ar: "تصدير PDF", en: "Export PDF" },
  importExcel: { ar: "استيراد Excel", en: "Import Excel" },
  downloadTemplate: { ar: "تحميل القالب", en: "Download Template" },
  importedRevenue: { ar: "تم استيراد {n} إيراد", en: "Imported {n} revenue entries" },
  importFailed: { ar: "فشل استيراد الملف", en: "Failed to import file" },
  importNoRows: { ar: "لم يتم العثور على صفوف صالحة", en: "No valid rows found" },
  noResults: { ar: "لا توجد نتائج", en: "No results" },
  paymentMethod: { ar: "طريقة الدفع", en: "Payment Method" },
  reference: { ar: "المرجع", en: "Reference" },
  notes: { ar: "ملاحظات", en: "Notes" },
  save: { ar: "حفظ", en: "Save" },
  cancel: { ar: "إلغاء", en: "Cancel" },
  prescription: { ar: "وصفات طبية", en: "Prescriptions" },
  otc: { ar: "أدوية بدون وصفة", en: "OTC" },
  cosmetics: { ar: "مستحضرات تجميل", en: "Cosmetics" },
  supplements: { ar: "مكملات غذائية", en: "Supplements" },
  medical: { ar: "مستلزمات طبية", en: "Medical Supplies" },
  other: { ar: "أخرى", en: "Other" },
  addedRevenue: { ar: "تم إضافة الإيراد بنجاح", en: "Revenue added successfully" },
  updatedRevenue: { ar: "تم تعديل الإيراد بنجاح", en: "Revenue updated successfully" },
  deletedRevenue: { ar: "تم حذف الإيراد", en: "Revenue deleted" },
  editRevenue: { ar: "تعديل الإيراد", en: "Edit Revenue" },
  confirmDeleteRevenue: { ar: "هل أنت متأكد من حذف هذا الإيراد؟", en: "Delete this revenue entry?" },
  actions: { ar: "إجراءات", en: "Actions" },
  edit: { ar: "تعديل", en: "Edit" },
  delete: { ar: "حذف", en: "Delete" },
  updatedPurchase: { ar: "تم تعديل الفاتورة", en: "Purchase updated" },
  updatedExpense: { ar: "تم تعديل المصروف", en: "Expense updated" },
  updatedSupplier: { ar: "تم تعديل المورد", en: "Supplier updated" },
  updatedDebt: { ar: "تم تعديل الدين", en: "Debt updated" },
  updatedStaff: { ar: "تم تعديل الموظف", en: "Staff member updated" },
  deletedRow: { ar: "تم الحذف", en: "Deleted" },
  undo: { ar: "تراجع", en: "Undo" },
  restoredSelected: { ar: "تم استرجاع العناصر", en: "Items restored" },
  confirmDeleteRow: { ar: "هل أنت متأكد من الحذف؟", en: "Delete this entry?" },
  selectedRows: { ar: "محدد", en: "selected" },
  selectAll: { ar: "تحديد الكل", en: "Select all" },
  deselectAll: { ar: "إلغاء تحديد الكل", en: "Deselect all" },
  clearSelection: { ar: "إلغاء التحديد", en: "Clear" },
  deleteSelected: { ar: "حذف المحدد", en: "Delete selected" },
  confirmDeleteSelected: { ar: "هل تريد حذف العناصر المحددة؟", en: "Delete the selected entries?" },
  deletedSelected: { ar: "تم حذف العناصر المحددة", en: "Selected entries deleted" },
  totalSelected: { ar: "إجمالي المعروض", en: "Total shown" },
  customers: { ar: "عدد العملاء", en: "Customers" },
  customersCount: { ar: "إجمالي العملاء", en: "Total Customers" },
  avgPerCustomer: { ar: "متوسط العميل", en: "Avg / Customer" },
  bank: { ar: "بنك", en: "Bank" },
  discount: { ar: "خصومات", en: "Discounts" },
  totalDiscounts: { ar: "إجمالي الخصومات", en: "Total Discounts" },
  netTotal: { ar: "صافي الإيراد", en: "Net Total" },
  netRevenue: { ar: "صافي الإيراد", en: "Net Revenue" },
  wasfatySales: { ar: "مبيعات وصفتي", en: "Wasfaty Sales" },
  dateLabel: { ar: "التاريخ", en: "Date" },
  autoGenerated: { ar: "يُولّد تلقائياً", en: "Auto-generated" },
  thisMonth: { ar: "هذا الشهر", en: "This Month" },
  thisWeek: { ar: "هذا الأسبوع", en: "This Week" },
  today: { ar: "اليوم", en: "Today" },
  filters: { ar: "الفلاتر", en: "Filters" },
  resetFilters: { ar: "إعادة تعيين", en: "Reset" },
  dateFrom: { ar: "من تاريخ", en: "From date" },
  dateTo: { ar: "إلى تاريخ", en: "To date" },
  amountMin: { ar: "أقل مبلغ", en: "Min amount" },
  amountMax: { ar: "أعلى مبلغ", en: "Max amount" },
  paymentAny: { ar: "كل طرق الدفع", en: "All payment methods" },
  cashOnly: { ar: "نقدي فقط", en: "Cash only" },
  bankOnly: { ar: "بنك فقط", en: "Bank only" },
  wasfatyOnly: { ar: "وصفتي فقط", en: "Wasfaty only" },
  groupBy: { ar: "تجميع حسب", en: "Group by" },
  groupNone: { ar: "بدون تجميع", en: "No grouping" },
  groupDay: { ar: "حسب اليوم", en: "By day" },
  groupWeek: { ar: "حسب الأسبوع", en: "By week" },
  groupMonth: { ar: "حسب الشهر", en: "By month" },
  groupYear: { ar: "حسب السنة", en: "By year" },
  entriesCount: { ar: "عدد القيود", en: "Entries" },
  presetThisWeek: { ar: "هذا الأسبوع", en: "This week" },
  presetThisMonth: { ar: "هذا الشهر", en: "This month" },
  presetThisYear: { ar: "هذه السنة", en: "This year" },
  presetAll: { ar: "كل الفترة", en: "All time" },

  // Expenses module
  expensesTitle: { ar: "إدارة المصروفات", en: "Expense Management" },
  expensesSubtitle: { ar: "تتبع جميع مصروفات الصيدلية والتشغيل", en: "Track all pharmacy operating expenses" },
  totalExpenses: { ar: "إجمالي المصروفات", en: "Total Expenses" },
  avgExpense: { ar: "متوسط المصروف", en: "Average Expense" },
  newExpense: { ar: "مصروف جديد", en: "New Expense" },
  searchExpenses: { ar: "بحث في المصروفات...", en: "Search expenses..." },
  addedExpense: { ar: "تم إضافة المصروف بنجاح", en: "Expense added successfully" },
  vendor: { ar: "المورد / الجهة", en: "Vendor" },
  annual: { ar: "مصروفات سنوية", en: "Annual Expenses" },
  founding: { ar: "مصروفات تأسيس", en: "Founding Expenses" },
  office: { ar: "أدوات مكتبية", en: "Office Supplies" },
  marketing: { ar: "تسويق", en: "Marketing" },
  phones: { ar: "تليفونات", en: "Phones" },
  electricity: { ar: "كهرباء", en: "Electricity" },
  bankFees: { ar: "رسوم بنكية", en: "Bank Fees" },
  rent: { ar: "إيجار", en: "Rent" },
  salaries: { ar: "رواتب شهرية", en: "Monthly Salaries" },
  medsPurchase: { ar: "مشتريات أدوية", en: "Medicines Purchase" },
  cosmeticsPurchase: { ar: "مشتريات كماليات", en: "Cosmetics Purchase" },
  milkPurchase: { ar: "مشتريات حليب", en: "Milk Purchase" },
  ownerDrawings: { ar: "مسحوبات الملاك (جاري الشركاء)", en: "Owner Drawings (Partners' Current Account)" },
  depreciation: { ar: "إهلاك الأصول الثابتة", en: "Depreciation Expense" },
  zakat: { ar: "زكاة سنوية", en: "Annual Zakat" },
  misc: { ar: "نثريات", en: "Miscellaneous" },
  receiptNo: { ar: "رقم الإيصال", en: "Receipt No." },

  // Purchases module
  purchasesTitle: { ar: "إدارة المشتريات", en: "Purchase Management" },
  purchasesSubtitle: { ar: "تتبع فواتير الشراء من الموردين والمخزون", en: "Track supplier invoices and inventory purchases" },
  totalPurchasesValue: { ar: "إجمالي المشتريات", en: "Total Purchases" },
  invoicesCount: { ar: "عدد الفواتير", en: "Invoices" },
  avgInvoice: { ar: "متوسط الفاتورة", en: "Avg. Invoice" },
  itemsPurchased: { ar: "الأصناف", en: "Items" },
  newPurchaseInvoice: { ar: "فاتورة شراء جديدة", en: "New Purchase Invoice" },
  searchPurchases: { ar: "بحث في المشتريات...", en: "Search purchases..." },
  addedPurchase: { ar: "تم تسجيل الفاتورة بنجاح", en: "Purchase recorded successfully" },
  supplier: { ar: "المورد", en: "Supplier" },
  invoiceNumber: { ar: "رقم الفاتورة", en: "Invoice #" },
  itemsCount: { ar: "عدد الأصناف", en: "# Items" },
  subtotal: { ar: "المجموع قبل الضريبة", en: "Subtotal" },
  vatAmount: { ar: "قيمة الضريبة", en: "VAT" },
  grandTotal: { ar: "الإجمالي", en: "Total" },
  paymentStatus: { ar: "حالة الدفع", en: "Payment Status" },
  paid: { ar: "مدفوعة", en: "Paid" },
  partial: { ar: "جزئية", en: "Partial" },
  unpaid: { ar: "غير مدفوعة", en: "Unpaid" },
  dueDate: { ar: "تاريخ الاستحقاق", en: "Due Date" },
  outstanding: { ar: "المتبقي", en: "Outstanding" },
  paidAmount: { ar: "المبلغ المدفوع", en: "Paid Amount" },

  // Suppliers module
  suppliersTitle: { ar: "إدارة الموردين", en: "Supplier Management" },
  suppliersSubtitle: { ar: "قاعدة بيانات الموردين والأرصدة المستحقة", en: "Supplier directory with balances and activity" },
  suppliersCount: { ar: "عدد الموردين", en: "Suppliers" },
  activeSuppliers: { ar: "موردون نشطون", en: "Active" },
  totalPayables: { ar: "إجمالي المستحق", en: "Total Payables" },
  topSupplier: { ar: "أعلى مورد", en: "Top Supplier" },
  newSupplier: { ar: "مورد جديد", en: "New Supplier" },
  searchSuppliers: { ar: "بحث في الموردين...", en: "Search suppliers..." },
  addedSupplier: { ar: "تم إضافة المورد بنجاح", en: "Supplier added successfully" },
  supplierName: { ar: "اسم المورد", en: "Supplier Name" },
  contactPerson: { ar: "الشخص المسؤول", en: "Contact Person" },
  phone: { ar: "الهاتف", en: "Phone" },
  email: { ar: "البريد الإلكتروني", en: "Email" },
  city: { ar: "المدينة", en: "City" },
  taxNumber: { ar: "الرقم الضريبي", en: "Tax #" },
  glnNumber: { ar: "رقم GLN", en: "GLN #" },
  nationalAddress: { ar: "العنوان الوطني", en: "National Address" },
  lastPurchase: { ar: "آخر فاتورة", en: "Last Purchase" },
  balance: { ar: "الرصيد", en: "Balance" },
  active: { ar: "نشط", en: "Active" },
  inactive: { ar: "غير نشط", en: "Inactive" },
  view: { ar: "عرض", en: "View" },

  // Staff module
  staffTitle: { ar: "إدارة الموظفين", en: "Staff Management" },
  staffSubtitle: { ar: "الموظفون والرواتب والمناوبات", en: "Employees, payroll and shifts" },
  staffCount: { ar: "عدد الموظفين", en: "Employees" },
  monthlyPayroll: { ar: "إجمالي الرواتب الشهرية", en: "Monthly Payroll" },
  onShift: { ar: "في المناوبة الآن", en: "On Shift Now" },
  avgSalary: { ar: "متوسط الراتب", en: "Avg. Salary" },
  newEmployee: { ar: "موظف جديد", en: "New Employee" },
  searchStaff: { ar: "بحث في الموظفين...", en: "Search staff..." },
  addedEmployee: { ar: "تم إضافة الموظف بنجاح", en: "Employee added successfully" },
  employeeName: { ar: "الاسم", en: "Name" },
  role: { ar: "الوظيفة", en: "Role" },
  salary: { ar: "الراتب", en: "Salary" },
  baseSalary: { ar: "الراتب الأساسي", en: "Base Salary" },
  overtimeSalary: { ar: "الراتب الإضافي", en: "Overtime" },
  housingAllowance: { ar: "بدل السكن", en: "Housing Allowance" },
  transportAllowance: { ar: "بدل الانتقال", en: "Transport Allowance" },
  totalSalary: { ar: "إجمالي الراتب", en: "Total Salary" },
  hireDate: { ar: "تاريخ التعيين", en: "Hire Date" },
  shift: { ar: "المناوبة", en: "Shift" },
  morning: { ar: "صباحية", en: "Morning" },
  evening: { ar: "مسائية", en: "Evening" },
  night: { ar: "ليلية", en: "Night" },
  off: { ar: "إجازة", en: "Off" },
  pharmacist: { ar: "صيدلي", en: "Pharmacist" },
  cashier: { ar: "أمين صندوق", en: "Cashier" },
  manager: { ar: "مدير فرع", en: "Manager" },
  assistant: { ar: "مساعد صيدلي", en: "Assistant" },
  cleaner: { ar: "عامل نظافة", en: "Cleaner" },
  hoursThisMonth: { ar: "ساعات هذا الشهر", en: "Hours MTD" },

  // Debts module
  debtsTitle: { ar: "إدارة الديون", en: "Debts Management" },
  debtsSubtitle: { ar: "الذمم المدينة والدائنة وحالة التحصيل", en: "Receivables, payables and collection status" },
  receivables: { ar: "ذمم مدينة (لنا)", en: "Receivables (owed to us)" },
  payables: { ar: "ذمم دائنة (علينا)", en: "Payables (we owe)" },
  netPosition: { ar: "صافي المركز", en: "Net Position" },
  overdueCount: { ar: "متأخرة", en: "Overdue" },
  newDebt: { ar: "دين جديد", en: "New Debt" },
  searchDebts: { ar: "بحث في الديون...", en: "Search debts..." },
  addedDebt: { ar: "تم تسجيل الدين بنجاح", en: "Debt recorded successfully" },
  debtType: { ar: "نوع الدين", en: "Type" },
  receivable: { ar: "مدين (لنا)", en: "Receivable" },
  payable: { ar: "دائن (علينا)", en: "Payable" },
  current: { ar: "ساري", en: "Current" },
  overdue: { ar: "متأخر", en: "Overdue" },
  settled: { ar: "مسدد", en: "Settled" },
  markSettled: { ar: "تم السداد", en: "Mark Settled" },
  agingBuckets: { ar: "أعمار الديون", en: "Aging" },
  bucket1: { ar: "شهر", en: "1 month" },
  bucket2: { ar: "شهرين", en: "2 months" },
  bucket3: { ar: "3 شهور", en: "3 months" },
  bucket4: { ar: "4 شهور", en: "4 months" },
  bucket5: { ar: "5 شهور", en: "5 months" },
  bucket5plus: { ar: "+5 شهور", en: "5+ months" },

  // Statements module
  statementsTitle: { ar: "القوائم المالية", en: "Financial Statements" },
  statementsSubtitle: { ar: "قائمة الدخل والميزانية العمومية والتدفقات النقدية", en: "P&L, Balance Sheet and Cash Flow" },
  profitLoss: { ar: "قائمة الدخل", en: "Profit & Loss" },
  balanceSheet: { ar: "الميزانية العمومية", en: "Balance Sheet" },
  cashFlowStatement: { ar: "التدفقات النقدية", en: "Cash Flow" },
  period: { ar: "الفترة", en: "Period" },
  monthly: { ar: "شهري", en: "Monthly" },
  quarterly: { ar: "ربع سنوي", en: "Quarterly" },
  yearly: { ar: "سنوي", en: "Yearly" },
  ytd: { ar: "منذ بداية العام", en: "Year-to-date" },
  grossRevenue: { ar: "إجمالي الإيرادات", en: "Gross Revenue" },
  costOfGoods: { ar: "تكلفة المبيعات", en: "Cost of Goods Sold" },
  grossProfit: { ar: "مجمل الربح", en: "Gross Profit" },
  operatingExpenses: { ar: "المصروفات التشغيلية", en: "Operating Expenses" },
  operatingIncome: { ar: "الدخل التشغيلي", en: "Operating Income" },
  vatExpense: { ar: "ضريبة القيمة المضافة", en: "VAT" },
  netIncome: { ar: "صافي الدخل", en: "Net Income" },
  margin: { ar: "الهامش", en: "Margin" },
  assets: { ar: "الأصول", en: "Assets" },
  liabilities: { ar: "الخصوم", en: "Liabilities" },
  equity: { ar: "حقوق الملكية", en: "Equity" },
  currentAssets: { ar: "أصول متداولة", en: "Current Assets" },
  fixedAssets: { ar: "أصول ثابتة", en: "Fixed Assets" },
  cashAndEquivalents: { ar: "النقد وما يعادله", en: "Cash & Equivalents" },
  accountsReceivable: { ar: "الذمم المدينة", en: "Accounts Receivable" },
  inventoryAsset: { ar: "المخزون", en: "Inventory" },
  equipment: { ar: "المعدات والأثاث", en: "Equipment & Fixtures" },
  currentLiabilities: { ar: "خصوم متداولة", en: "Current Liabilities" },
  longTermLiabilities: { ar: "خصوم طويلة الأجل", en: "Long-term Liabilities" },
  accountsPayable: { ar: "الذمم الدائنة", en: "Accounts Payable" },
  vatPayable: { ar: "ضريبة مستحقة", en: "VAT Payable" },
  loans: { ar: "قروض", en: "Loans" },
  ownerEquity: { ar: "رأس المال", en: "Owner's Capital" },
  retainedEarnings: { ar: "أرباح محتجزة", en: "Retained Earnings" },
  totalAssets: { ar: "إجمالي الأصول", en: "Total Assets" },
  totalLiabilities: { ar: "إجمالي الخصوم", en: "Total Liabilities" },
  totalEquity: { ar: "إجمالي حقوق الملكية", en: "Total Equity" },
  liabilitiesAndEquity: { ar: "إجمالي الخصوم وحقوق الملكية", en: "Total Liab. & Equity" },
  operatingActivities: { ar: "الأنشطة التشغيلية", en: "Operating Activities" },
  investingActivities: { ar: "الأنشطة الاستثمارية", en: "Investing Activities" },
  financingActivities: { ar: "الأنشطة التمويلية", en: "Financing Activities" },
  otherActivity: { ar: "أنشطة أخرى", en: "Other Activity" },
  otherIncome: { ar: "إيرادات أخرى (ذمم مدينة)", en: "Other Income (Receivables)" },
  otherExpense: { ar: "مصروفات أخرى (ذمم دائنة)", en: "Other Expense (Payables)" },
  cashFromSales: { ar: "متحصلات من المبيعات", en: "Cash from Sales" },
  cashFromReceivables: { ar: "تحصيل ذمم مدينة", en: "Collections from Receivables" },
  cashToExpenses: { ar: "مدفوعات للمصروفات", en: "Cash to Expenses" },
  cashToSuppliers: { ar: "مدفوعات للموردين", en: "Cash to Suppliers" },
  cashToPayables: { ar: "سداد ذمم دائنة", en: "Payments on Payables" },
  netCashChange: { ar: "صافي التغير في النقد", en: "Net Change in Cash" },
  openingBalance: { ar: "الرصيد الافتتاحي", en: "Opening Balance" },
  closingBalance: { ar: "الرصيد الختامي", en: "Closing Balance" },
  openingBalances: { ar: "الأرصدة الافتتاحية", en: "Opening Balances" },
  openingBalancesHint: { ar: "تُضاف هذه القيم إلى القوائم المالية كأرصدة بداية المدة", en: "These values are added to the financial statements as opening period balances" },
  openingCash: { ar: "نقدية بداية المدة", en: "Opening Cash" },
  openingBank: { ar: "بنك بداية المدة", en: "Opening Bank" },
  openingInventory: { ar: "مخزون بداية المدة", en: "Opening Inventory" },
  openingInventorySubtotal: { ar: "قيمة المخزون (بدون ضريبة)", en: "Inventory Value (excl. VAT)" },
  openingInventoryVat: { ar: "قيمة ضريبة القيمة المضافة", en: "VAT Amount" },
  openingInventoryTotal: { ar: "الإجمالي شامل الضريبة", en: "Total (incl. VAT)" },
  closingInventory: { ar: "مخزون نهاية المدة", en: "Closing Inventory" },
  closingInventorySubtotal: { ar: "قيمة المخزون (بدون ضريبة)", en: "Inventory Value (excl. VAT)" },
  closingInventoryVat: { ar: "قيمة ضريبة القيمة المضافة", en: "VAT Amount" },
  closingInventoryTotal: { ar: "الإجمالي شامل الضريبة", en: "Total (incl. VAT)" },
  openingInventoryVatCarry: { ar: "ضريبة مخزون بداية المدة (مرحّلة)", en: "Opening Inventory VAT (carry-forward)" },
  closingInventoryVatMemo: { ar: "ضريبة مخزون نهاية المدة (للعلم)", en: "Closing Inventory VAT (memo)" },
  openingDrawerCustody: { ar: "عهدة الدرج بداية المدة", en: "Opening Drawer Custody" },
  drawerCustody: { ar: "عهدة الدرج", en: "Cash Drawer Custody" },
  openingEquipment: { ar: "التجهيزات في أول المدة", en: "Opening Equipment & Setup" },
  equipmentOpening: { ar: "تجهيزات أول المدة", en: "Equipment & Setup (Opening)" },
  accumulatedDepreciation: { ar: "مجمع الإهلاك", en: "Accumulated Depreciation" },
  openingSupplierDebts: { ar: "ديون الموردين بداية المدة", en: "Opening Supplier Debts" },
  openingFixedAssets: { ar: "الأصول الثابتة الافتتاحية الأخرى", en: "Other Opening Fixed Assets" },
  addFixedAsset: { ar: "إضافة أصل ثابت", en: "Add Fixed Asset" },
  assetName: { ar: "اسم الأصل", en: "Asset Name" },
  noFixedAssetsYet: { ar: "لا توجد أصول ثابتة افتتاحية", en: "No opening fixed assets yet" },
  supplierLedger: { ar: "كشف حساب مورد", en: "Supplier Ledger" },
  selectSupplier: { ar: "اختر المورد", en: "Select supplier" },
  runningBalance: { ar: "الرصيد المتحرك", en: "Running Balance" },
  noTransactions: { ar: "لا توجد حركات في الفترة المحددة", en: "No transactions in the selected period" },
  invoiceAmount: { ar: "قيمة الفاتورة", en: "Invoice Amount" },
  paymentAmount: { ar: "المدفوع", en: "Payment" },
  noSuppliersYet: { ar: "لا يوجد موردون مضافون بعد", en: "No suppliers added yet" },
  editOpenings: { ar: "تعديل الأرصدة", en: "Edit Balances" },
  printStatement: { ar: "طباعة", en: "Print" },
  inflow: { ar: "وارد", en: "Inflow" },
  outflow: { ar: "صادر", en: "Outflow" },
  filterMonth: { ar: "هذا الشهر", en: "This Month" },
  filterQuarter: { ar: "هذا الربع", en: "This Quarter" },
  filterYear: { ar: "هذه السنة", en: "This Year" },
  filterAllTime: { ar: "كامل الفترة", en: "All Time" },
  filterCustom: { ar: "مخصص", en: "Custom" },
  filterPeriod: { ar: "فترة التقرير", en: "Report Period" },
  applyFilter: { ar: "تطبيق", en: "Apply" },

  // VAT module
  vatTitle: { ar: "ضريبة القيمة المضافة", en: "VAT Management" },
  vatSubtitle: { ar: "تقارير ضريبة المبيعات والمشتريات والإقرار الضريبي", en: "Sales & purchases VAT reporting and returns" },
  outputVat: { ar: "ضريبة المخرجات (المبيعات)", en: "Output VAT (Sales)" },
  inputVat: { ar: "ضريبة المدخلات (المشتريات)", en: "Input VAT (Purchases)" },
  outputVatPayable: { ar: "ضريبة المخرجات المستحقة", en: "Output VAT Payable" },
  cashOnHand: { ar: "النقد في الصندوق", en: "Cash on Hand" },
  netVat: { ar: "صافي الضريبة المستحقة", en: "Net VAT Payable" },
  netVatPayable: { ar: "صافي الضريبة المستحقة للمصلحة", en: "Net VAT Payable" },
  vatSummary: { ar: "ملخص ضريبة القيمة المضافة", en: "VAT Summary" },
  vatRate: { ar: "النسبة", en: "Rate" },
  vatRefundable: { ar: "ضريبة قابلة للاسترداد", en: "VAT Refundable" },
  taxableAmount: { ar: "المبلغ الخاضع للضريبة", en: "Taxable Amount" },
  totalWithVat: { ar: "الإجمالي شامل الضريبة", en: "Total Incl. VAT" },
  filingPeriod: { ar: "فترة الإقرار", en: "Filing Period" },
  q1: { ar: "الربع الأول", en: "Q1" },
  q2: { ar: "الربع الثاني", en: "Q2" },
  q3: { ar: "الربع الثالث", en: "Q3" },
  q4: { ar: "الربع الرابع", en: "Q4" },
  salesVat: { ar: "ضريبة المبيعات", en: "Sales VAT" },
  purchasesVat: { ar: "ضريبة المشتريات", en: "Purchases VAT" },
  vatReturn: { ar: "الإقرار الضريبي", en: "VAT Return" },
  invoiceCount: { ar: "عدد الفواتير", en: "Invoices" },
  effectiveRate: { ar: "النسبة الفعلية", en: "Effective Rate" },
  vatBreakdown: { ar: "تفصيل ضريبة القيمة المضافة", en: "VAT Breakdown" },
  breakdownByRate: { ar: "حسب النسبة الضريبية", en: "By VAT Rate" },
  breakdownByCategory: { ar: "حسب الفئة", en: "By Category" },
  standardRate: { ar: "النسبة القياسية 15%", en: "Standard 15%" },
  zeroRated: { ar: "نسبة صفرية 0%", en: "Zero-Rated 0%" },
  shareOfTotal: { ar: "النسبة من الإجمالي", en: "Share of Total" },
  month: { ar: "الشهر", en: "Month" },
  quarter: { ar: "الربع", en: "Quarter" },
  reportsTitle: { ar: "التقارير", en: "Reports Center" },
  reportsSubtitle: { ar: "تقارير جاهزة للتشغيل والتصدير", en: "Ready-to-run reports for your business" },
  reportCatalog: { ar: "كتالوج التقارير", en: "Report Catalog" },
  recentReports: { ar: "التقارير الأخيرة", en: "Recent Reports" },
  runReport: { ar: "تشغيل", en: "Run" },
  catFinancial: { ar: "مالي", en: "Financial" },
  catSales: { ar: "المبيعات", en: "Sales" },
  catInventory: { ar: "المشتريات والمخزون", en: "Purchases & Inventory" },
  catHr: { ar: "الموارد البشرية", en: "HR" },
  catTax: { ar: "الضرائب", en: "Tax" },
  catCompliance: { ar: "الامتثال", en: "Compliance" },
  rptPL: { ar: "قائمة الدخل", en: "Profit & Loss Statement" },
  rptPLDesc: { ar: "ملخص الإيرادات والمصروفات وصافي الربح", en: "Revenue, expenses and net profit summary" },
  rptBS: { ar: "الميزانية العمومية", en: "Balance Sheet" },
  rptBSDesc: { ar: "الأصول والخصوم وحقوق الملكية", en: "Assets, liabilities and equity snapshot" },
  rptCF: { ar: "التدفقات النقدية", en: "Cash Flow Statement" },
  rptCFDesc: { ar: "صافي التغير في النقد عبر الأنشطة", en: "Net change in cash across activities" },
  rptSales: { ar: "تقرير المبيعات اليومية", en: "Daily Sales Report" },
  rptSalesDesc: { ar: "المبيعات حسب الفئة وطريقة الدفع", en: "Sales by category and payment method" },
  rptTopProducts: { ar: "أكثر المنتجات مبيعاً", en: "Top Products" },
  rptTopProductsDesc: { ar: "المنتجات الأعلى مساهمة في الإيراد", en: "Highest revenue contributing items" },
  rptPurchases: { ar: "تقرير المشتريات", en: "Purchases Report" },
  rptPurchasesDesc: { ar: "أوامر الشراء حسب المورد والحالة", en: "Purchase orders by supplier and status" },
  rptSuppliers: { ar: "أداء الموردين", en: "Supplier Performance" },
  rptSuppliersDesc: { ar: "تصنيف الموردين حسب الموثوقية والإنفاق", en: "Suppliers ranked by reliability and spend" },
  rptStaff: { ar: "كشف الرواتب", en: "Payroll Summary" },
  rptStaffDesc: { ar: "ملخص رواتب الموظفين والساعات", en: "Staff salaries and hours overview" },
  rptVat: { ar: "إقرار ضريبة القيمة المضافة", en: "VAT Return" },
  rptVatDesc: { ar: "ضريبة المخرجات والمدخلات والصافي", en: "Output, input and net VAT position" },
  rptDebts: { ar: "أعمار الديون", en: "Debts Aging" },
  rptDebtsDesc: { ar: "الذمم المدينة والدائنة حسب العمر", en: "Receivables and payables by age" },
  rptAudit: { ar: "سجل التدقيق", en: "Audit Log" },
  rptAuditDesc: { ar: "أحدث التغييرات في النظام", en: "Recent system activity trail" },
  lastRun: { ar: "آخر تشغيل", en: "Last run" },
  reportName: { ar: "اسم التقرير", en: "Report" },
  generatedAt: { ar: "وقت الإنشاء", en: "Generated" },
  format: { ar: "الصيغة", en: "Format" },
  download: { ar: "تنزيل", en: "Download" },
  noRecentReports: { ar: "لا توجد تقارير حديثة", en: "No recent reports yet" },
  preview: { ar: "معاينة", en: "Preview" },
  reportPreview: { ar: "معاينة التقرير", en: "Report Preview" },
  rowsCount: { ar: "عدد الصفوف", en: "Rows" },
  closePreview: { ar: "إغلاق", en: "Close" },

  // Settings module
  settingsTitle: { ar: "الإعدادات", en: "Settings" },
  settingsSubtitle: { ar: "تخصيص النظام والتفضيلات والصلاحيات", en: "Customize your workspace, preferences and permissions" },
  settingsSaved: { ar: "تم حفظ الإعدادات", en: "Settings saved successfully" },
  settingsReset: { ar: "تمت استعادة الإعدادات الافتراضية", en: "Settings restored to defaults" },
  resetDefaults: { ar: "استعادة الافتراضي", en: "Reset to defaults" },
  saveChanges: { ar: "حفظ التغييرات", en: "Save changes" },
  unsavedChanges: { ar: "لديك تغييرات غير محفوظة", en: "You have unsaved changes" },

  // Settings - sections
  secBusiness: { ar: "بيانات المنشأة", en: "Business Profile" },
  secBusinessDesc: { ar: "اسم الصيدلية والشعار وبيانات الاتصال", en: "Pharmacy identity, logo and contact details" },
  secLocalization: { ar: "اللغة والمنطقة", en: "Localization" },
  secLocalizationDesc: { ar: "اللغة والعملة والمنطقة الزمنية", en: "Language, currency and timezone" },
  secAppearance: { ar: "المظهر", en: "Appearance" },
  secAppearanceDesc: { ar: "السمة والكثافة وتفضيلات العرض", en: "Theme, density and display options" },
  secTax: { ar: "إعدادات الضرائب", en: "Tax Settings" },
  secTaxDesc: { ar: "نسبة الضريبة وفترة الإقرار", en: "VAT rates and filing period" },
  secInvoicing: { ar: "الفواتير", en: "Invoicing" },
  secInvoicingDesc: { ar: "ترقيم الفواتير والشروط الافتراضية", en: "Invoice numbering and default terms" },
  secNotifications: { ar: "الإشعارات", en: "Notifications" },
  secNotificationsDesc: { ar: "تنبيهات المخزون والديون والضرائب", en: "Inventory, debt and tax alerts" },
  secUsers: { ar: "المستخدمون والصلاحيات", en: "Users & Permissions" },
  secUsersDesc: { ar: "إدارة فريق العمل والأدوار", en: "Manage team members and roles" },
  secIntegrations: { ar: "التكاملات", en: "Integrations" },
  secIntegrationsDesc: { ar: "البوابات والخدمات المتصلة", en: "Connected services and gateways" },
  secSecurity: { ar: "الأمان", en: "Security" },
  secSecurityDesc: { ar: "كلمة المرور والتحقق بخطوتين", en: "Password and two-factor authentication" },
  secBackup: { ar: "النسخ الاحتياطي", en: "Backup & Data" },
  secBackupDesc: { ar: "تصدير واستيراد ومسح البيانات", en: "Export, import and reset data" },

  // Business profile fields
  businessName: { ar: "اسم المنشأة", en: "Business Name" },
  legalName: { ar: "الاسم القانوني", en: "Legal Name" },
  crNumber: { ar: "السجل التجاري", en: "Commercial Reg. #" },
  vatNumber: { ar: "الرقم الضريبي", en: "VAT Number" },
  address: { ar: "العنوان", en: "Address" },
  website: { ar: "الموقع الإلكتروني", en: "Website" },
  logoUrl: { ar: "رابط الشعار", en: "Logo URL" },

  // Localization
  language: { ar: "اللغة", en: "Language" },
  arabic: { ar: "العربية", en: "Arabic" },
  english: { ar: "الإنجليزية", en: "English" },
  timezone: { ar: "المنطقة الزمنية", en: "Timezone" },
  dateFormat: { ar: "تنسيق التاريخ", en: "Date Format" },
  numberFormat: { ar: "تنسيق الأرقام", en: "Number Format" },

  // Appearance
  theme: { ar: "السمة", en: "Theme" },
  themeDark: { ar: "داكن", en: "Dark" },
  themeLight: { ar: "فاتح", en: "Light" },
  density: { ar: "الكثافة", en: "Density" },
  comfortable: { ar: "مريحة", en: "Comfortable" },
  compact: { ar: "مدمجة", en: "Compact" },
  sidebarCollapsed: { ar: "تصغير الشريط الجانبي افتراضياً", en: "Collapse sidebar by default" },

  // Tax
  defaultVatRate: { ar: "النسبة الافتراضية", en: "Default VAT Rate (%)" },
  filingFrequency: { ar: "دورية الإقرار", en: "Filing Frequency" },
  taxInclusive: { ar: "الأسعار شاملة الضريبة", en: "Prices include VAT" },

  // Invoicing
  invoicePrefix: { ar: "بادئة الفاتورة", en: "Invoice Prefix" },
  nextInvoiceNumber: { ar: "رقم الفاتورة التالي", en: "Next Invoice #" },
  paymentTermsDays: { ar: "مهلة السداد (أيام)", en: "Payment Terms (days)" },
  defaultNotes: { ar: "ملاحظات افتراضية على الفاتورة", en: "Default invoice notes" },

  // Notifications
  notifyLowStock: { ar: "تنبيه نفاد المخزون", en: "Low stock alerts" },
  notifyOverdue: { ar: "تنبيه الديون المتأخرة", en: "Overdue debt reminders" },
  notifyVat: { ar: "تذكير موعد الإقرار الضريبي", en: "VAT filing reminders" },
  notifyDailySummary: { ar: "ملخص يومي بالبريد", en: "Daily email summary" },
  emailChannel: { ar: "البريد الإلكتروني", en: "Email" },
  smsChannel: { ar: "رسالة نصية", en: "SMS" },
  pushChannel: { ar: "إشعار داخل التطبيق", en: "In-app push" },

  // Users & roles
  inviteUser: { ar: "دعوة مستخدم", en: "Invite User" },
  userName: { ar: "الاسم", en: "Name" },
  userRole: { ar: "الصلاحية", en: "Role" },
  userStatus: { ar: "الحالة", en: "Status" },
  roleAdmin: { ar: "مدير عام", en: "Admin" },
  roleAccountant: { ar: "محاسب", en: "Accountant" },
  rolePharmacist: { ar: "صيدلي", en: "Pharmacist" },
  roleViewer: { ar: "اطلاع فقط", en: "Viewer" },
  invitePending: { ar: "دعوة معلقة", en: "Pending invite" },

  // Integrations
  intZatca: { ar: "هيئة الزكاة والضريبة (ZATCA)", en: "ZATCA e-invoicing" },
  intZatcaDesc: { ar: "ربط الفوترة الإلكترونية المرحلة الثانية", en: "Phase 2 e-invoicing integration" },
  intMada: { ar: "بوابة مدى للدفع", en: "Mada payment gateway" },
  intMadaDesc: { ar: "قبول مدفوعات البطاقات المحلية", en: "Accept local card payments" },
  intWhatsapp: { ar: "إشعارات واتساب للأعمال", en: "WhatsApp Business" },
  intWhatsappDesc: { ar: "إرسال الفواتير والتذكيرات", en: "Send invoices and reminders" },
  intDrive: { ar: "نسخ احتياطي على Google Drive", en: "Google Drive backup" },
  intDriveDesc: { ar: "نسخ تلقائي للبيانات يومياً", en: "Automatic daily data backup" },
  connect: { ar: "ربط", en: "Connect" },
  connected: { ar: "متصل", en: "Connected" },
  disconnect: { ar: "فصل", en: "Disconnect" },
  notConnected: { ar: "غير متصل", en: "Not connected" },
  connecting: { ar: "جاري الربط...", en: "Connecting..." },
  disconnecting: { ar: "جاري الفصل...", en: "Disconnecting..." },
  connectTitle: { ar: "ربط الخدمة", en: "Connect service" },
  disconnectTitle: { ar: "تأكيد فصل الخدمة", en: "Confirm disconnect" },
  connectIntro: { ar: "أدخل بيانات الاعتماد لإكمال ربط الخدمة بحسابك.", en: "Enter your credentials to complete the connection." },
  disconnectWarn: { ar: "سيتم إيقاف المزامنة وقد تحتاج لإعادة الربط لاحقاً.", en: "Sync will stop and you may need to reconnect later." },
  confirmConnect: { ar: "تأكيد الربط", en: "Confirm connect" },
  confirmDisconnect: { ar: "تأكيد الفصل", en: "Confirm disconnect" },
  connectedSince: { ar: "متصل منذ", en: "Connected since" },
  account: { ar: "الحساب", en: "Account" },
  apiKey: { ar: "مفتاح API", en: "API key" },
  workspaceId: { ar: "معرّف المساحة", en: "Workspace ID" },
  phoneNumber: { ar: "رقم الهاتف", en: "Phone number" },
  merchantId: { ar: "معرّف التاجر", en: "Merchant ID" },
  intConnectedToast: { ar: "تم ربط الخدمة بنجاح", en: "Service connected successfully" },
  intDisconnectedToast: { ar: "تم فصل الخدمة", en: "Service disconnected" },
  required: { ar: "مطلوب", en: "Required" },

  // Security
  changePassword: { ar: "تغيير كلمة المرور", en: "Change password" },
  twoFactor: { ar: "التحقق بخطوتين", en: "Two-factor authentication" },
  sessionTimeout: { ar: "انتهاء الجلسة بعد (دقيقة)", en: "Session timeout (minutes)" },
  loginAlerts: { ar: "تنبيه عند تسجيل دخول جديد", en: "Alert on new sign-in" },
  lastSignIn: { ar: "آخر تسجيل دخول", en: "Last sign-in" },

  // Backup
  exportAll: { ar: "تصدير كل البيانات", en: "Export all data" },
  importData: { ar: "استيراد بيانات", en: "Import data" },
  clearData: { ar: "مسح بيانات النظام", en: "Clear system data" },
  clearDataWarn: { ar: "لا يمكن التراجع عن هذا الإجراء", en: "This action cannot be undone" },
  autoBackup: { ar: "النسخ الاحتياطي التلقائي", en: "Automatic backup" },
  daily: { ar: "يومي", en: "Daily" },
  weekly: { ar: "أسبوعي", en: "Weekly" },
  never: { ar: "غير مفعّل", en: "Never" },

  // Login
  signIn: { ar: "تسجيل الدخول", en: "Sign in" },
  signOut: { ar: "تسجيل الخروج", en: "Sign out" },
  signInTitle: { ar: "أهلاً بعودتك", en: "Welcome back" },
  signInSubtitle: { ar: "سجّل دخولك للمتابعة إلى لوحة التحكم", en: "Sign in to continue to your dashboard" },
  password: { ar: "كلمة المرور", en: "Password" },
  rememberMe: { ar: "تذكرني", en: "Remember me" },
  forgotPassword: { ar: "نسيت كلمة المرور؟", en: "Forgot password?" },
  continueWithGoogle: { ar: "المتابعة عبر Google", en: "Continue with Google" },
  continueWithApple: { ar: "المتابعة عبر Apple", en: "Continue with Apple" },
  orContinueWith: { ar: "أو تابع باستخدام", en: "or continue with" },
  noAccount: { ar: "ليس لديك حساب؟", en: "Don't have an account?" },
  contactSales: { ar: "تواصل مع المبيعات", en: "Contact sales" },
  signedIn: { ar: "تم تسجيل الدخول بنجاح", en: "Signed in successfully" },
  signedOut: { ar: "تم تسجيل الخروج", en: "Signed out" },
  demoCreds: { ar: "بيانات تجريبية: admin@pharm.sa / demo1234", en: "Demo: admin@pharm.sa / demo1234" },
  invalidCreds: { ar: "بريد أو كلمة مرور غير صحيحة", en: "Invalid email or password" },
  trustedBy: { ar: "موثوق به من قِبل صيدليات في الخليج", en: "Trusted by pharmacies across the Gulf" },

  // Branches
  secBranches: { ar: "الفروع", en: "Branches" },
  secBranchesDesc: { ar: "إدارة فروع الصيدلية والمدراء", en: "Manage pharmacy locations and managers" },
  newBranch: { ar: "فرع جديد", en: "New Branch" },
  branchName: { ar: "اسم الفرع", en: "Branch Name" },
  branchCode: { ar: "الرمز", en: "Code" },
  branchManager: { ar: "المدير", en: "Manager" },
  branchAddress: { ar: "العنوان", en: "Address" },
  addedBranch: { ar: "تم إضافة الفرع", en: "Branch added" },
  removedBranch: { ar: "تم حذف الفرع", en: "Branch removed" },
  setMain: { ar: "تعيين كرئيسي", en: "Set as main" },
  mainBranch: { ar: "الفرع الرئيسي", en: "Main branch" },
  remove: { ar: "حذف", en: "Remove" },

  // AI / Coming Soon
  aiCenter: { ar: "ميزات الذكاء الاصطناعي", en: "AI Features" },
  aiSubtitle: { ar: "ميزات قادمة لتحليل وتنبؤ أداء صيدليتك", en: "Upcoming intelligence to analyze and forecast your pharmacy" },
  comingSoon: { ar: "قريباً", en: "Coming Soon" },
  notifyMe: { ar: "أعلمني عند الإطلاق", en: "Notify me at launch" },
  notifyAdded: { ar: "سنخبرك عند توفر هذه الميزة", en: "We'll notify you when this is available" },
  aiForecast: { ar: "التنبؤ المالي بالذكاء الاصطناعي", en: "AI Financial Forecast" },
  aiForecastDesc: { ar: "توقّع إيرادات ومصروفات الشهر القادم باستخدام تحليل الاتجاهات", en: "Predict next month revenue and expenses using trend analysis" },
  smartInsights: { ar: "رؤى ذكية أسبوعية", en: "Smart Weekly Insights" },
  smartInsightsDesc: { ar: "ملخص أسبوعي تلقائي يبرز التغيرات المهمة في أدائك", en: "Auto-generated weekly summary highlighting key shifts in your performance" },
  barcodeScanner: { ar: "ماسح الباركود", en: "Barcode Scanner" },
  barcodeScannerDesc: { ar: "تكامل باركود المنتجات لإدارة المخزون", en: "Product barcode integration for inventory management" },
  multiBranchRollup: { ar: "تجميع متعدد الفروع", en: "Multi-Branch Consolidation" },
  multiBranchRollupDesc: { ar: "تقارير موحّدة عبر جميع فروع صيدليتك", en: "Roll-up reports across all your pharmacy branches" },
  mobileApp: { ar: "تطبيق الجوال", en: "Mobile App" },
  mobileAppDesc: { ar: "تطبيق React Native مرافق للوصول السريع", en: "React Native companion app for on-the-go access" },
  ai: { ar: "الذكاء الاصطناعي", en: "AI" },

  // Organizations / Multi-tenant
  organizations: { ar: "المنشآت", en: "Organizations" },
  organization: { ar: "المنشأة", en: "Organization" },
  currentOrganization: { ar: "المنشأة الحالية", en: "Current Organization" },
  switchOrganization: { ar: "تبديل المنشأة", en: "Switch Organization" },
  manageOrganizations: { ar: "إدارة المنشآت", en: "Manage Organizations" },
  createOrganization: { ar: "إنشاء منشأة جديدة", en: "Create New Organization" },
  editOrganization: { ar: "تعديل المنشأة", en: "Edit Organization" },
  deleteOrganization: { ar: "حذف المنشأة", en: "Delete Organization" },
  organizationName: { ar: "اسم المنشأة", en: "Organization Name" },
  businessType: { ar: "نوع النشاط", en: "Business Type" },
  pharmacyType: { ar: "صيدلية", en: "Pharmacy" },
  clinicType: { ar: "عيادة", en: "Clinic" },
  companyType: { ar: "شركة", en: "Company" },
  retailType: { ar: "تجزئة", en: "Retail" },
  commercialRegister: { ar: "السجل التجاري", en: "Commercial Register" },
  noOrganizations: { ar: "لا توجد منشآت بعد — أنشئ أول منشأة لك", en: "No organizations yet — create your first one" },
  organizationCreated: { ar: "تم إنشاء المنشأة", en: "Organization created" },
  organizationUpdated: { ar: "تم تحديث المنشأة", en: "Organization updated" },
  organizationDeleted: { ar: "تم حذف المنشأة", en: "Organization deleted" },
  confirmDeleteOrg: { ar: "هل أنت متأكد من حذف هذه المنشأة؟ سيتم حذف جميع بياناتها.", en: "Delete this organization? All its data will be removed." },
  roleOwner: { ar: "مالك", en: "Owner" },
  roleCashier: { ar: "كاشير", en: "Cashier" },
  create: { ar: "إنشاء", en: "Create" },
  organizationLogo: { ar: "شعار المنشأة", en: "Organization logo" },
  uploadLogo: { ar: "رفع شعار", en: "Upload logo" },
  changeLogo: { ar: "تغيير الشعار", en: "Change logo" },
  removeLogo: { ar: "إزالة الشعار", en: "Remove logo" },
  uploadingLogo: { ar: "جارٍ الرفع...", en: "Uploading..." },
  logoTooLarge: { ar: "حجم الصورة كبير جداً (الحد الأقصى 2 ميجا)", en: "Logo too large (max 2MB)" },
};

interface AppCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  toggleLang: () => void;
  theme: Theme;
  setTheme: (t: Theme) => void;
  toggleTheme: () => void;
  t: (k: keyof typeof dict) => string;
  fmt: (n: number) => string;
  dir: "rtl" | "ltr";
}

const Ctx = createContext<AppCtx | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ar");
  const [theme, setThemeState] = useState<Theme>("dark");

  useEffect(() => {
    const savedLang = (typeof localStorage !== "undefined" && localStorage.getItem("pl_lang")) as Lang | null;
    const savedTheme = (typeof localStorage !== "undefined" && localStorage.getItem("pl_theme")) as Theme | null;
    if (savedLang) setLangState(savedLang);
    if (savedTheme) setThemeState(savedTheme);
  }, []);

  const dir: "rtl" | "ltr" = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    document.documentElement.classList.remove("dark", "light");
    document.documentElement.classList.add(theme);
  }, [lang, theme, dir]);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof localStorage !== "undefined") localStorage.setItem("pl_lang", l);
  };
  const setTheme = (t: Theme) => {
    setThemeState(t);
    if (typeof localStorage !== "undefined") localStorage.setItem("pl_theme", t);
  };

  const t = (k: keyof typeof dict) => dict[k]?.[lang] ?? String(k);
  const fmt = (n: number) =>
    new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-US", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
      useGrouping: false,
    }).format(n);

  return (
    <Ctx.Provider
      value={{
        lang,
        setLang,
        toggleLang: () => setLang(lang === "ar" ? "en" : "ar"),
        theme,
        setTheme,
        toggleTheme: () => setTheme(theme === "dark" ? "light" : "dark"),
        t,
        fmt,
        dir,
      }}
    >
      {children}
    </Ctx.Provider>
  );
}

export function useApp() {
  const v = useContext(Ctx);
  if (!v) throw new Error("useApp must be used within AppProvider");
  return v;
}
