/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VatRouteImport } from './routes/vat'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SupplierPaymentsRouteImport } from './routes/supplier-payments'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalEntriesRouteImport } from './routes/journal-entries'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as ChartOfAccountsRouteImport } from './routes/chart-of-accounts'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryReportsRouteImport } from './routes/inventory.reports'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryOperationsRouteImport } from './routes/inventory.operations'

const VatRoute = VatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPaymentsRoute = SupplierPaymentsRouteImport.update({
  id: '/supplier-payments',
  path: '/supplier-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesRoute = JournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartOfAccountsRoute = ChartOfAccountsRouteImport.update({
  id: '/chart-of-accounts',
  path: '/chart-of-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryReportsRoute = InventoryReportsRouteImport.update({
  id: '/inventory/reports',
  path: '/inventory/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOperationsRoute = InventoryOperationsRouteImport.update({
  id: '/inventory/operations',
  path: '/inventory/operations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/backup': typeof BackupRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/statements': typeof StatementsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat': typeof VatRoute
  '/inventory/operations': typeof InventoryOperationsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/reports': typeof InventoryReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/backup': typeof BackupRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/statements': typeof StatementsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat': typeof VatRoute
  '/inventory/operations': typeof InventoryOperationsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/reports': typeof InventoryReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/backup': typeof BackupRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/debts': typeof DebtsRoute
  '/expenses': typeof ExpensesRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/statements': typeof StatementsRoute
  '/supplier-payments': typeof SupplierPaymentsRoute
  '/suppliers': typeof SuppliersRoute
  '/vat': typeof VatRoute
  '/inventory/operations': typeof InventoryOperationsRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/reports': typeof InventoryReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/backup'
    | '/chart-of-accounts'
    | '/debts'
    | '/expenses'
    | '/journal-entries'
    | '/login'
    | '/organizations'
    | '/purchases'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/staff'
    | '/statements'
    | '/supplier-payments'
    | '/suppliers'
    | '/vat'
    | '/inventory/operations'
    | '/inventory/products'
    | '/inventory/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/backup'
    | '/chart-of-accounts'
    | '/debts'
    | '/expenses'
    | '/journal-entries'
    | '/login'
    | '/organizations'
    | '/purchases'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/staff'
    | '/statements'
    | '/supplier-payments'
    | '/suppliers'
    | '/vat'
    | '/inventory/operations'
    | '/inventory/products'
    | '/inventory/reports'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/backup'
    | '/chart-of-accounts'
    | '/debts'
    | '/expenses'
    | '/journal-entries'
    | '/login'
    | '/organizations'
    | '/purchases'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/staff'
    | '/statements'
    | '/supplier-payments'
    | '/suppliers'
    | '/vat'
    | '/inventory/operations'
    | '/inventory/products'
    | '/inventory/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BackupRoute: typeof BackupRoute
  ChartOfAccountsRoute: typeof ChartOfAccountsRoute
  DebtsRoute: typeof DebtsRoute
  ExpensesRoute: typeof ExpensesRoute
  JournalEntriesRoute: typeof JournalEntriesRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StatementsRoute: typeof StatementsRoute
  SupplierPaymentsRoute: typeof SupplierPaymentsRoute
  SuppliersRoute: typeof SuppliersRoute
  VatRoute: typeof VatRoute
  InventoryOperationsRoute: typeof InventoryOperationsRoute
  InventoryProductsRoute: typeof InventoryProductsRoute
  InventoryReportsRoute: typeof InventoryReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vat': {
      id: '/vat'
      path: '/vat'
      fullPath: '/vat'
      preLoaderRoute: typeof VatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-payments': {
      id: '/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/supplier-payments'
      preLoaderRoute: typeof SupplierPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries': {
      id: '/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-of-accounts': {
      id: '/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof ChartOfAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/reports': {
      id: '/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof InventoryReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/operations': {
      id: '/inventory/operations'
      path: '/inventory/operations'
      fullPath: '/inventory/operations'
      preLoaderRoute: typeof InventoryOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BackupRoute: BackupRoute,
  ChartOfAccountsRoute: ChartOfAccountsRoute,
  DebtsRoute: DebtsRoute,
  ExpensesRoute: ExpensesRoute,
  JournalEntriesRoute: JournalEntriesRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StatementsRoute: StatementsRoute,
  SupplierPaymentsRoute: SupplierPaymentsRoute,
  SuppliersRoute: SuppliersRoute,
  VatRoute: VatRoute,
  InventoryOperationsRoute: InventoryOperationsRoute,
  InventoryProductsRoute: InventoryProductsRoute,
  InventoryReportsRoute: InventoryReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
